### ISSUE TITLE
Ability to deselect station type

### ISSUE THREAD

**Issue by kubiix** [kryojenik/LTN_Combinator_Modernized#15]
Currently the combinator GUI allows to uncheck all variants of station type (requester, provider, depot)
But when GUI is closed, with no type selected the requester type is selected by default.

I would like to use only the output signals part of combinator to act as smarter constant combinator allowing to specify amount by stacks count

**Comment by kryojenik** [comment]
In that case leave it checked as a provider.  LTN technically doesn't configure a stop as either a Provider or Requester.   All LTN stops are both.  If they receive positive signals the will offer (provide) that item to the LTN network.  If they receive a negative signal the will request that item from the network.   An LTN stop can do both.  A Depot is mutually exclusive of this and has a specific signal.

The Provider and Requester checkboxes serve to infer stop behavior base on signals.  Unchecking the provider box will cause the combinator to set a very high provider threshold effectively making it impossible for the stop to advertise any inventory -- thus restricting it to requester behaviors.  Checking the requestor box serves to uncheck the provider box.  Otherwise they are status indicators.

To use it a standard constant combinator, leave the provider box checked.  This is the default (empty) state of the combinator.  Any signal that is added as a negative will result in both the provider and requester boxes being checked.

This is not a change that will be implemented.
