### ISSUE TITLE
Provider only setup sends a "Request Threshold 2.1G" signal 

### ISSUE THREAD

**Issue by hgschmie** [kryojenik/LTN_Combinator_Modernized#53]
Setting up an LTN combinator like this:

<img width="828" alt="Screenshot 2024-02-01 at 13 33 56" src="https://github.com/kryojenik/LTN_Combinator_Modernized/assets/39495/654da218-d3d7-4f03-8c86-771f3ffd7234">

results in the combinator sending a request threshold signal:

<img width="246" alt="Screenshot 2024-02-01 at 13 34 47" src="https://github.com/kryojenik/LTN_Combinator_Modernized/assets/39495/a5404be5-54dc-462e-90c8-fdd186be0c3a">

If I check the "Enable Requester" box but leave everything else unchanged, the signal disappears.

Base game 1.1.101, LTN 1.18.6, LTN Combinator Modernized 2.1.4 flib 0.13.0
MacOS 13.6.3, arm64

**Comment by kryojenik** [comment]
This is expected.  In order to effectively "disable" the request capability, a very high (MAX_INT - [2^31-1]) threshold is sent into the LTN input.  The display shows '1000' in RED to show what would be used when the "Disable Requester" is unchecked.  It is RED to show that no signal would be emitted from the combinator as it is the default configured in the LTN mod settings.

**Comment by hgschmie** [comment]
Thanks for the explanation. Maybe add a sentence to the docs to explain that behavior? 

In any case, thank you for the LTN combinator. I use it all over the place and it is great.
